# Generated by Django 5.2.13 on 2026-04-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='redeemed_points',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_spend',
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage applied on this transaction (0 if none)', max_digits=5, verbose_name='Discount %'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='points',
            field=models.IntegerField(help_text='Points earned in this transaction', verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earn', 'Earn')], default='earn', max_length=20, verbose_name='Type'),
        ),
    ]
