volumes:
  beyond_prodprodpostgres_data: {}
  beyond_prodprodpostgres_data_backups: {}
  beyond_prodproddjango_media: {}
  beyond_prodproddjango_staticfiles: {}
  
  beyond_prodprodredis_data: {}
  
networks:
  beyond_trend:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: beyond_trend_beyond_prodproddjango
    volumes:
      - beyond_prodproddjango_media:/app/beyond_trend/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - beyond_trend
    restart: always

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: beyond_trend_beyond_prodprodpostgres
    volumes:
      - beyond_prodprodpostgres_data:/var/lib/postgresql/data
      - beyond_prodprodpostgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - beyond_trend
    restart: always

  redis:
    image: docker.io/redis:6
    
    volumes:
      - beyond_prodprodredis_data:/data
    
    networks:
      - beyond_trend
    restart: always

  celeryworker:
    <<: *django
    image: beyond_trend_beyond_prodprodceleryworker
    command: /start-celeryworker
    networks:
      - beyond_trend
    restart: always

  celerybeat:
    <<: *django
    image: beyond_trend_beyond_prodprodcelerybeat
    command: /start-celerybeat
    networks:
      - beyond_trend
    restart: always

  flower:
    <<: *django
    image: beyond_trend_beyond_prodprodflower
    command: /start-flower
    networks:
      - beyond_trend
    restart: always

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: beyond_trend_beyond_prodprodnginx
    depends_on:
      - django
    volumes:
      - beyond_prodproddjango_media:/app/media
    ports:
      - 9119:80
    networks:
      - beyond_trend
    restart: always
