# Generated by Django 5.2.1 on 2026-04-03 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('brand_name', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('barcode', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Barcode')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('size', models.CharField(max_length=20, verbose_name='Size')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
