# Generated by Django 5.2.1 on 2026-04-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_options_alter_product_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylog',
            old_name='variant',
            new_name='product',
        ),
    ]
