# Generated by Django 5.2.1 on 2026-04-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_color_to_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Code'),
        ),
    ]
