# Generated by Django 5.2.1 on 2026-04-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_category_product_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_website',
            field=models.BooleanField(default=True, verbose_name='Show in Website'),
        ),
    ]
