# Generated by Django 5.2.1 on 2026-04-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_shoesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoesale',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
            preserve_default=False,
        ),
    ]
