# Generated by Django 5.2.1 on 2026-04-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_shoesale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoesale',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
    ]
